In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as pt
%matplotlib inline
import plotly.offline as py
import plotly.graph_objs as go

In [3]:
flower_dataset = pd.read_csv('IRIS.csv')

In [4]:
flower_dataset.head()

sepal_length  sepal_width  petal_length  petal_width      species
0           5.1          3.5           1.4          0.2  Iris-setosa
1           4.9          3.0           1.4          0.2  Iris-setosa
2           4.7          3.2           1.3          0.2  Iris-setosa
3           4.6          3.1           1.5          0.2  Iris-setosa
4           5.0          3.6           1.4          0.2  Iris-setosa

In [5]:
len(flower_dataset)

150

In [7]:
from sklearn.model_selection import train_test_split
train_test_split()
#not using this method to maintain same praportion.

In [8]:
flower_dataset.columns

Index(['sepal_length', 'sepal_width', 'petal_length', 'petal_width',
       'species'],
      dtype='object')

In [9]:
flower_dataset['species'].value_counts()

Iris-virginica     50
Iris-setosa        50
Iris-versicolor    50
Name: species, dtype: int64

In [20]:
from sklearn.model_selection import StratifiedShuffleSplit
split = StratifiedShuffleSplit(n_splits=1, test_size=0.2, random_state=29)
print(split)

for train_idx, test_idx in split.split(flower_dataset, flower_dataset['species']):
    Strat_train = flower_dataset.loc[train_idx]
    Strat_test = flower_dataset.loc[test_idx]

StratifiedShuffleSplit(n_splits=1, random_state=29, test_size=0.2,
            train_size=None)


In [18]:
Strat_train['species'].value_counts()

Iris-virginica     40
Iris-setosa        40
Iris-versicolor    40
Name: species, dtype: int64

In [19]:
Strat_test['species'].value_counts()

Iris-virginica     10
Iris-setosa        10
Iris-versicolor    10
Name: species, dtype: int64

In [21]:
Strat_train.head()

sepal_length  sepal_width  petal_length  petal_width          species
60            5.0          2.0           3.5          1.0  Iris-versicolor
45            4.8          3.0           1.4          0.3      Iris-setosa
26            5.0          3.4           1.6          0.4      Iris-setosa
17            5.1          3.5           1.4          0.3      Iris-setosa
133           6.3          2.8           5.1          1.5   Iris-virginica

In [22]:
X_train = Strat_train.drop('species', axis=1)
X_train

sepal_length  sepal_width  petal_length  petal_width
60            5.0          2.0           3.5          1.0
45            4.8          3.0           1.4          0.3
26            5.0          3.4           1.6          0.4
17            5.1          3.5           1.4          0.3
133           6.3          2.8           5.1          1.5
..            ...          ...           ...          ...
39            5.1          3.4           1.5          0.2
38            4.4          3.0           1.3          0.2
63            6.1          2.9           4.7          1.4
109           7.2          3.6           6.1          2.5
145           6.7          3.0           5.2          2.3

[120 rows x 4 columns]

In [23]:
y_train = Strat_train[['species']]

In [24]:
y_train

species
60   Iris-versicolor
45       Iris-setosa
26       Iris-setosa
17       Iris-setosa
133   Iris-virginica
..               ...
39       Iris-setosa
38       Iris-setosa
63   Iris-versicolor
109   Iris-virginica
145   Iris-virginica

[120 rows x 1 columns]

# trying Stochastic Gradient algorithm

In [26]:
from sklearn.linear_model import SGDClassifier
sgd_cls = SGDClassifier()
sgd_cls.fit(X_train, y_train)

c:\users\prasad\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:744: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



SGDClassifier(alpha=0.0001, average=False, class_weight=None,
              early_stopping=False, epsilon=0.1, eta0=0.0, fit_intercept=True,
              l1_ratio=0.15, learning_rate='optimal', loss='hinge',
              max_iter=1000, n_iter_no_change=5, n_jobs=None, penalty='l2',
              power_t=0.5, random_state=None, shuffle=True, tol=0.001,
              validation_fraction=0.1, verbose=0, warm_start=False)

In [34]:
class_list = sgd_cls.classes_

In [31]:
random_data_point = flower_dataset.iloc[27]
random_data_point.drop('species', inplace=True)
random_data_point

sepal_length    5.2
sepal_width     3.5
petal_length    1.5
petal_width     0.2
Name: 27, dtype: object

In [36]:
predict_list = sgd_cls.decision_function([random_data_point])
list_index = np.argmax(predict_list)
predict_result = class_list[list_index]
predict_result

'Iris-setosa'

In [33]:
flower_dataset.iloc[27]

sepal_length            5.2
sepal_width             3.5
petal_length            1.5
petal_width             0.2
species         Iris-setosa
Name: 27, dtype: object

In [37]:
from sklearn.metrics import confusion_matrix
confusion_matrix(
)

In [41]:
len(Strat_test)
Strat_test.iloc[4]

sepal_length               7.7
sepal_width                3.8
petal_length               6.7
petal_width                2.2
species         Iris-virginica
Name: 117, dtype: object

In [42]:
X_test = Strat_test.drop('species', axis=1)
y_test = Strat_test[['species']]

In [43]:
#for i in range(len(Strat_test)):
X_test.head()

sepal_length  sepal_width  petal_length  petal_width
64            5.6          2.9           3.6          1.3
113           5.7          2.5           5.0          2.0
24            4.8          3.4           1.9          0.2
50            7.0          3.2           4.7          1.4
117           7.7          3.8           6.7          2.2

In [44]:
y_test.head()

species
64   Iris-versicolor
113   Iris-virginica
24       Iris-setosa
50   Iris-versicolor
117   Iris-virginica

In [46]:
sgd_cls.predict([X_test.iloc[10]])

array(['Iris-setosa'], dtype='<U15')

In [47]:
y_test.iloc[10]

species    Iris-setosa
Name: 32, dtype: object

In [49]:
for i in range(len(X_test)):
    predicted_category = sgd_cls.predict([X_test.iloc[i]])
    actual_category = y_test.iloc[i]
    print("Actual_category",actual_category,"predicted_category",predicted_category)

Actual_category species    Iris-versicolor
Name: 64, dtype: object predicted_category ['Iris-setosa']
Actual_category species    Iris-virginica
Name: 113, dtype: object predicted_category ['Iris-virginica']
Actual_category species    Iris-setosa
Name: 24, dtype: object predicted_category ['Iris-setosa']
Actual_category species    Iris-versicolor
Name: 50, dtype: object predicted_category ['Iris-setosa']
Actual_category species    Iris-virginica
Name: 117, dtype: object predicted_category ['Iris-virginica']
Actual_category species    Iris-setosa
Name: 41, dtype: object predicted_category ['Iris-setosa']
Actual_category species    Iris-virginica
Name: 101, dtype: object predicted_category ['Iris-virginica']
Actual_category species    Iris-versicolor
Name: 68, dtype: object predicted_category ['Iris-versicolor']
Actual_category species    Iris-setosa
Name: 33, dtype: object predicted_category ['Iris-setosa']
Actual_category species    Iris-versicolor
Name: 94, dtype: object predicted_cate

In [54]:
from sklearn.model_selection import cross_val_predict
y_pred = cross_val_predict(sgd_cls, X_train, y_train, cv=3)


from sklearn.metrics import confusion_matrix
confusion_matrix(y_train, y_pred)

c:\users\prasad\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:744: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

c:\users\prasad\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:744: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

c:\users\prasad\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:744: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



array([[40,  0,  0],
       [16, 13, 11],
       [ 0,  2, 38]], dtype=int64)

In [57]:
from sklearn.model_selection import cross_val_score
cross_val_score(sgd_cls, X_train, y_train, scoring="accuracy", cv=3)

c:\users\prasad\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:744: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

c:\users\prasad\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:744: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

c:\users\prasad\appdata\local\programs\python\python37\lib\site-packages\sklearn\utils\validation.py:744: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



array([0.65 , 0.675, 0.675])

## trying Naive Bayes classifier

In [59]:
from sklearn.naive_bayes import GaussianNB
naive_clf = GaussianNB()
naive_clf.fit(X_train, y_train)

c:\users\prasad\appdata\local\programs\python\python37\lib\site-packages\sklearn\naive_bayes.py:207: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



GaussianNB(priors=None, var_smoothing=1e-09)

In [60]:
naive_clf.predict([X_test.iloc[22]])

array(['Iris-virginica'], dtype='<U15')

In [62]:
y_test.iloc[22]

species    Iris-virginica
Name: 107, dtype: object

In [63]:
cross_val_score(naive_clf, X_train, y_train, scoring="accuracy", cv=3)

c:\users\prasad\appdata\local\programs\python\python37\lib\site-packages\sklearn\naive_bayes.py:207: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

c:\users\prasad\appdata\local\programs\python\python37\lib\site-packages\sklearn\naive_bayes.py:207: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().

c:\users\prasad\appdata\local\programs\python\python37\lib\site-packages\sklearn\naive_bayes.py:207: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



array([0.975, 0.925, 0.95 ])

In [64]:
naive_clf.classes_

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype='<U15')

In [76]:
def testing(index):
    for i in range(len(index)):
        predicted_class = naive_clf.predict([index.iloc[i]])
        actual_class = y_test.iloc[i]
        print(predicted_class[0], actual_class)

In [77]:
testing(X_test)

Iris-versicolor species    Iris-versicolor
Name: 64, dtype: object
Iris-virginica species    Iris-virginica
Name: 113, dtype: object
Iris-setosa species    Iris-setosa
Name: 24, dtype: object
Iris-versicolor species    Iris-versicolor
Name: 50, dtype: object
Iris-virginica species    Iris-virginica
Name: 117, dtype: object
Iris-setosa species    Iris-setosa
Name: 41, dtype: object
Iris-virginica species    Iris-virginica
Name: 101, dtype: object
Iris-versicolor species    Iris-versicolor
Name: 68, dtype: object
Iris-setosa species    Iris-setosa
Name: 33, dtype: object
Iris-versicolor species    Iris-versicolor
Name: 94, dtype: object
Iris-setosa species    Iris-setosa
Name: 32, dtype: object
Iris-virginica species    Iris-virginica
Name: 143, dtype: object
Iris-virginica species    Iris-virginica
Name: 141, dtype: object
Iris-setosa species    Iris-setosa
Name: 21, dtype: object
Iris-setosa species    Iris-setosa
Name: 34, dtype: object
Iris-virginica species    Iris-virginica
Name: 1

In [71]:
y_test.head()

species
64   Iris-versicolor
113   Iris-virginica
24       Iris-setosa
50   Iris-versicolor
117   Iris-virginica

In [78]:
#y_scores = cross_val_predict(naive_clf, X_train, y_train, cv=3, method="decision_function")

c:\users\prasad\appdata\local\programs\python\python37\lib\site-packages\sklearn\naive_bayes.py:207: DataConversionWarning:

A column-vector y was passed when a 1d array was expected. Please change the shape of y to (n_samples, ), for example using ravel().



AttributeError: 'GaussianNB' object has no attribute 'decision_function'